# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/settings.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(250, 275)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(230, 250))
        MainWindow.setMaximumSize(QtCore.QSize(250, 275))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 186, 214))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.animaltype = QtWidgets.QLineEdit(self.layoutWidget)
        self.animaltype.setWhatsThis("")
        self.animaltype.setInputMask("")
        self.animaltype.setCursorPosition(0)
        self.animaltype.setDragEnabled(False)
        self.animaltype.setReadOnly(False)
        self.animaltype.setClearButtonEnabled(True)
        self.animaltype.setObjectName("animaltype")
        self.horizontalLayout_5.addWidget(self.animaltype)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.animalbreed = QtWidgets.QLineEdit(self.layoutWidget)
        self.animalbreed.setStatusTip("")
        self.animalbreed.setWhatsThis("")
        self.animalbreed.setAccessibleName("")
        self.animalbreed.setInputMask("")
        self.animalbreed.setCursorPosition(0)
        self.animalbreed.setDragEnabled(False)
        self.animalbreed.setReadOnly(False)
        self.animalbreed.setClearButtonEnabled(True)
        self.animalbreed.setObjectName("animalbreed")
        self.horizontalLayout_4.addWidget(self.animalbreed)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.animalweight = QtWidgets.QSpinBox(self.layoutWidget)
        self.animalweight.setMinimum(1)
        self.animalweight.setSingleStep(1)
        self.animalweight.setObjectName("animalweight")
        self.horizontalLayout.addWidget(self.animalweight)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.animalage = QtWidgets.QSpinBox(self.layoutWidget)
        self.animalage.setMinimum(1)
        self.animalage.setSingleStep(1)
        self.animalage.setObjectName("animalage")
        self.horizontalLayout_2.addWidget(self.animalage)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.animalsex = QtWidgets.QComboBox(self.layoutWidget)
        self.animalsex.setObjectName("animalsex")
        self.animalsex.addItem("")
        self.animalsex.addItem("")
        self.horizontalLayout_3.addWidget(self.animalsex)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.downloadButton = QtWidgets.QPushButton(self.layoutWidget)
        self.downloadButton.setObjectName("downloadButton")
        self.horizontalLayout_6.addWidget(self.downloadButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(70, 240, 87, 29))
        self.saveButton.setObjectName("saveButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Данные о животном"))
        self.label_5.setText(_translate("MainWindow", "Вид"))
        self.animaltype.setToolTip(_translate("MainWindow", "Кошка, собака, кролик"))
        self.label_4.setText(_translate("MainWindow", "Порода"))
        self.animalbreed.setToolTip(_translate("MainWindow", "Порода животного"))
        self.label.setText(_translate("MainWindow", "Вес"))
        self.label_2.setText(_translate("MainWindow", "Возраст "))
        self.label_3.setText(_translate("MainWindow", "Пол"))
        self.animalsex.setItemText(0, _translate("MainWindow", "М"))
        self.animalsex.setItemText(1, _translate("MainWindow", "Ж"))
        self.label_6.setText(_translate("MainWindow", "Загрузить фото"))
        self.downloadButton.setToolTip(_translate("MainWindow", "Выбрать фото на компьютере"))
        self.downloadButton.setText(_translate("MainWindow", "Загрузить"))
        self.saveButton.setText(_translate("MainWindow", "Сохранить"))


